TeamBasedInquiryLearning/precalculus

.devcontainer.json, source/03-PR/06.ptx
Gives an example of generating graphs (in this case, rational functions) via `<sageplot>` and packaging them up nicely in a side-by-side.  Closes #7
=> Regenerate graphs using Sageplot, closes #7

project.ptx, publication/publication.ptx, publication/slides.ptx, xsl/slides.xsl
Generates slides as in the other two books.
=> Generate slides

LICENSE, LICENSE.md, README.md, source/meta/copyright.ptx
I suggest we bounce this off the precal contributors on Tuesday to confirm before merging.
=> line up licensing with other TBIL library works

source/meta/frontmatter.ptx
With everyone having successfully made a PR, seems like a good time to add everyone as authors to the project.
=> Add authors

source/03-PR/04.ptx
attempt for pull request draft file
=> PR4 draft Precalculus

site/index.html
This will redirect https://teambasedinquirylearning.github.io/precalculus/ to https://teambasedinquirylearning.github.io/precalculus/2024/
=> add redirect to root of deployment

source/03-PR/02.ptx
added a second activity discussing maximum revenue where students find the equation first.
=> added a second activity

source/03-PR/02.ptx
=> Fix LaTeX in <m/> tags

source/03-PR/05.ptx
The only section I couldn't figure out was the spacing for part c of activity 1.5.5. How do I write the end behavior so that a new line starts with "As x goes to..."?
=> Ready to sync to main (need help with one thing)

source/03-PR/02.ptx
=> Kathy-11-7

source/03-PR/02.ptx
definitely didn't want a trick question... changed it on my desmos and found answers and then forgot to change in pretext.
=> updated value of part c question 2

source/03-PR/06.ptx
=> pr6 updates

exercises/outcomes/PR/PR6/template.xml
See @AbbyANoble's comment in #43
=> Remove unfortunate typo

source/03-PR/06.ptx
Changes made from discussions; still a few things needing updating and will work on that over break!
=> PR6 updates 12/15

source/03-PR/02.ptx
made suggested updates from discussion to PR2
=> Kathy 1-19

source/03-PR/01.ptx, source/03-PR/02.ptx, source/03-PR/03.ptx, source/03-PR/04.ptx, source/03-PR/05.ptx, source/03-PR/06.ptx
Add exercise links to module PR, closes #42
=> Add exercise links to module PR, closes #42

source/03-PR/06.ptx
Reverts TeamBasedInquiryLearning/precalculus#58 
(I borked the merge somehow -- should not try to resolve merge conflicts before coffee)
(Also unclear why there were merge conflicts at all in #58)
=> Revert "PR6 updates"

source/04-PR/01.ptx, source/04-PR/05.ptx
=> Stub out Module EQ (#63)

source/04-PR/03.ptx
I have another version so is there a way to ignore this one? The one called draft is the most finalized version. Can I delete the other one?
=> PR4_03_changes

source/01-EQ/01.ptx
added most of section material for EQ1
=> EQ1 update 2-22 Kathy

source/01-EQ/02.ptx
first two examples. One or two more about mixtures to come!
=> EQ2 First draft

source/01-EQ/01.ptx
updated EQ 1 from feedback left.  still need a bit of help with number lines and then I can fully finish.
=> EQ1 - feedback updates

source/01-EQ/04.ptx
completed the first portion of EQ3 - still have to add activities for >= abs inequalities and the definition and then some fluency problems.
=> EQ 4 first updates

source/01-EQ/02.ptx
Incorporated Kathy's edits. Need to add scaffolding to 1.2.9
=> updates on EQ2

source/01-EQ/01.ptx, source/01-EQ/04.ptx
included number lines in 1.1 finished material in 1.4
=> included number lines in 1.1 finished material in 1.4

source/01-EQ/02.ptx
1.2.9 scaffolding is completed, and 1.2.10 is fluency
=> last bit of EQ2

source/04-PR/01.ptx
=> Issue PR-1 tweaks #90 - Ready to merge

source/04-PR/02.ptx
=> updated issues

source/02-FN/06.ptx
added first set of content for FN6
=> first pass at FN6

source/02-FN/02.ptx
I used the answer tag for the first time in this one. Let me know if this is the correct way so that it is easily removed for a student edition!
=> first draft of FN2

source/02-FN/04.ptx
this is my first attempt at FN 4 (regardless of what I named the branch).....
=> Kathy-FN-6

source/02-FN/06.ptx
=> updated FN 6 from discussion

source/04-PR/03.ptx
=> Edits_Take 2 again

source/02-FN/05.ptx
=> fn5-first-draft

source/02-FN/02.ptx
=> Fixes from FN2 discussion.

source/02-FN/02.ptx, source/02-FN/05.ptx
Finished first draft of FN5. 
Also a small change to FN2, giving a remark an xml:id so I could refer back to it.
=> FN5 updates

source/02-FN/05.ptx
Fixes from #129 after #135 was merged.
=> More FN5 updates!

source/03-LF/02.ptx
=> first draft of LF2

source/02-FN/05.ptx
=> close #136

source/01-EQ/01.ptx, source/01-EQ/03.ptx, source/01-EQ/04.ptx, source/01-EQ/05.ptx, source/01-EQ/06.ptx, source/01-EQ/07.ptx, source/02-FN/01.ptx, source/02-FN/03.ptx, source/02-FN/04.ptx, source/02-FN/05.ptx, source/02-FN/06.ptx, source/04-PR/01.ptx, source/04-PR/02.ptx, source/04-PR/03.ptx, source/04-PR/04.ptx, source/04-PR/05.ptx, source/04-PR/06.ptx
=> Add missing <statement>s to <task>s

.github/workflows/on-pull-request.yml, project.ptx
Makes Codechat show instructor version by default
=> switch default target to instructor

source/03-LF/02.ptx
made updates from feedback #141
=> updates from feedback

source/03-LF/06.ptx
=> initial draft of LF6

source/03-LF/07.ptx
=> first try LF7

source/03-LF/01.ptx
=> remove detect_poles (due to Sage 9.2 bug)

source/02-FN/01.ptx, source/02-FN/02.ptx, source/02-FN/03.ptx, source/03-LF/01.ptx, source/03-LF/03.ptx, source/04-PR/01.ptx, source/04-PR/05.ptx, source/04-PR/06.ptx
Removes the other unneeded `detect_poles` (the bug only seems to appear when there isn't an asymptote).
=> Fix graphs

source/03-LF/03.ptx
updated with Tonya's changes from #142 and finished last bit
=> LF3-round-two

source/01-EQ/06.ptx
addresses #177
Regarding 1.6.3, I added more to the observation above the question.
Regarding columns, I made all "small" answers as two columns.
=> EQ6 tweaks

source/02-FN/05.ptx
addresses #182
I also updated all the answers to the format we decided on in the style guide.
=> FN5 tweaks

source/03-LF/05.ptx
=> remove numbered tables

source/01-EQ/02.ptx
Added in answers.
Removed <table> in a few places to prevent numbering.
Decided that #173 is a wontfix for now!
=> EQ2 tweaks

source/02-FN/02.ptx
=> FN2 tweaks

source/02-FN/01.ptx
=> Fixed Issue FN1 Tweaks #178

source/01-EQ/03.ptx
=> Fixed EQ3 Tweaks #174

source/02-FN/04.ptx
fixed issues 181 and 159 along with comments in discussion
=> fixed issues 181 and 159 along with comments in discussion

source/01-EQ/01.ptx
=> EQ1 issues fixes

source/01-EQ/04.ptx
=> fix EQ4 issues

source/02-FN/06.ptx
=> FN6-issues

source/03-LF/06.ptx
updated LF 6 from discussion #145
=> LF6 updates

source/03-LF/03.ptx
updates from last bit of feedback (#142)
added in missing answers
=> updates to LF3

source/03-LF/05.ptx
=> LF5-round-two

source/03-LF/06.ptx
added one more activity to include multiplication with elimination
=> L6 second update

source/05-EL/05.ptx
Found one more thing that I should have caught in #215 that was causing an error in the print builds
=> Typo in EL5

source/02-FN/04.ptx
=> Switch text labels to raw strings

source/05-EL/02.ptx
For some reason that I can't figure out, the graph in the answer of 5.2.9c is not appearing correctly for me. In my codechat window, it's just showing the graph for part b (which is what I copy/pasted from to start). Help please!
=> EL2 first draft

source/02-FN/03.ptx
=> Second attempt to fix FN3 Tweaks #180

source/05-EL/01.ptx
=> EL1 first update

source/05-EL/04.ptx
Ready to go, except I'm making an issue for one wonky graph!
=> EL4 first draft

source/03-LF/05.ptx
=> LF5 tweaks

source/03-LF/03.ptx
=> LF3 tweaks

source/05-EL/04.ptx
=> Remove duplicate xml:id

source/03-LF/04.ptx
=> intersect at right angle

source/05-EL/02.ptx
=> EL2 round two

source/05-EL/03.ptx
=> first draft of EL3

project.ptx
Closes #269, I believe without breaking anything.
=> Remove commentary stringparam

source/04-PR/04.ptx
=> Pr4Sec4_Updates redo

source/01-EQ/07.ptx
=> EQ7Updates redo

source/01-EQ/readiness.ptx
Added one more review problem based on discussion during meeting.
=> EQ readiness update

source/05-EL/02.ptx
Added in asymptotes to more graphs.
=> EL2 round three

source/04-PR/readiness.ptx
added additional things from comments on outline
=> second updates to FN readiness

source/03-LF/02.ptx
=> fix issue LF2 Tweaks #234

source/05-EL/01.ptx, source/05-EL/03.ptx
=> updates to EL3 from feedback

source/03-LF/06.ptx
=> fix issue LF6 Tweaks #238

source/05-EL/01.ptx
=> updates to EL1 from feedback

source/03-LF/07.ptx
fixes #239
also tried to fix comma problem when I noticed it.
=> fixes issue LF7 Tweaks #239

source/05-EL/04.ptx
Ready, except my graphs are no longer showing up in 5.4.6 and 5.4.7! They were working before this PR, and I updated the answer (not the graph portion) to match what I did on the similar questions in EL2, but they aren't compiling correctly. Not sure if it's a CodeChat issue (which I seem to have with graphs a lot!) or a me issue. :)
=> EL4 round two

source/05-EL/02.ptx, source/05-EL/04.ptx
=> EL2 and EL4 tweaks

source/05-EL/readiness.ptx
=> EL readiness edits

source/05-EL/06.ptx
=> Fixed EL6 Tweaks #300

source/05-EL/05.ptx
=> Fixed EL5 Tweaks #299

source/05-EL/07.ptx
=> Fixed EL7 Tweaks #301

source/04-PR/readiness.ptx
=> updates to PR readiness from feedback

source/05-EL/03.ptx
=> fixes issue EL3 Tweaks #297

source/05-EL/01.ptx
=> issue EL1 Tweaks #295

source/01-EQ/readiness.ptx
=> EQ readiness updates

exercises/outcomes/PR/PR2/generator.sage
One of the scenarios in this problem displays $q(t)$ in the generator, but then produces a function of $x$.  This should fix that.
=> Change variable in Checkit PR-2

exercises/outcomes/PR/PR2/template.xml
=> Remove extra 'in'

source/04-PR/03.ptx
=> PR3 updates

exercises/bank.xml, exercises/outcomes/PR/PR3/generator.sage, exercises/outcomes/PR/PR3/template.xml, exercises/outcomes/PR/PR4/generator.sage, exercises/outcomes/PR/PR4/template.xml, exercises/outcomes/PR/PR5/generator.sage, exercises/outcomes/PR/PR5/template.xml, source/04-PR/03.ptx, source/04-PR/04.ptx, source/04-PR/05.ptx, source/04-PR/outcomes/03.ptx, source/04-PR/outcomes/04.ptx, source/04-PR/outcomes/05.ptx
=> Reorder PR sections

source/03-LF/05.ptx
=> addition to LF5

source/04-PR/05.ptx
new and improved PR5 (zeros of polynomials using factor, remainder, rational root)
=> updates to new PR 5

source/04-PR/03.ptx
=> Add to PR3 #407

source/04-PR/outcomes/03.ptx, source/04-PR/outcomes/05.ptx
=> Objective updates

source/01-EQ/outcomes/01.ptx, source/01-EQ/outcomes/04.ptx, source/01-EQ/outcomes/06.ptx
=> Update EQ Objectives

source/01-EQ/outcomes/main.ptx, source/02-FN/outcomes/main.ptx, source/03-LF/outcomes/main.ptx, source/04-PR/outcomes/main.ptx, source/05-EL/outcomes/main.ptx
=> big ideas in precalc

source/02-FN/03.ptx, source/04-PR/01.ptx
=> terminology consistency

source/01-EQ/01.ptx
=> answers for EQ1 (and fixed a typo)

source/05-EL/05.ptx, source/05-EL/outcomes/04.ptx
"Logarithms" in the title of EL5 wasn't capitalized.
Title of EL4 was repeated in the objective.
=> Fix typos/style

source/01-EQ/01.ptx, source/01-EQ/04.ptx
=> updates to EQ4 answers

source/01-EQ/06.ptx
=> updated EQ6 answers

source/05-EL/02.ptx
removed periods after letter answer choices to match style guide
=> updated EL2 answers

source/04-PR/05.ptx, source/05-EL/04.ptx
=> updated PR5 answers and fixed one answer in EL4

source/01-EQ/01.ptx, source/01-EQ/04.ptx
Partially addresses  #192 and #424.  See the latter for where @kathypinzon identified `<answer>`s that needed number lines, so I went ahead and added them in via sageplots.
=> Add number lines to answers

source/04-PR/03.ptx
added answers - graph to 4.3.20 isn't displaying properly but I can't figure out why.
=> updated answers to new PR3

source/04-PR/06.ptx
answered all but the last two - I need Abby to check those questions because I think she wants the denominator to be +6 instead of -6
=> almost all answers to PR6

source/03-LF/01.ptx
=> Move answer within task

source/04-PR/06.ptx
=> Fix 4.6.19

sage/common.sage, source/01-EQ/07.ptx
=> Incorporate Tonya's feedback
